# Site settings
name: LinkOrz's Blog
email: seline100@126.com
author: Liangxl
url: http://www.linkorz.xyz
resume_site: http://www.linkorz.xyz/Resume.io/
github: https://github.com/seline100/
baseurl: ""
description: Stay hungry,stay foolish
meta_description: 梁小林;个人博客;求知若饥,虚心若愚;
motto: It's our wits that make us men.
banner: 求知若饥,虚心若愚。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: seline100
rouge: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : seline100
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light